In [1]:
### 01. 데이터 준비
import pandas as pd
data = { "eng": ["b", "c", "a", "d"] }
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


eng
0   b
1   c
2   a
3   d

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [4]:
en_x = LabelEncoder()
df['라벨인코딩'] = en_x.fit_transform( df['eng'] )
df

eng  라벨인코딩
0   b      1
1   c      2
2   a      0
3   d      3

순서가 상관이 있다면 원핫 인코딩 !!

In [5]:
onehot = OneHotEncoder()
val = df['라벨인코딩'].values.reshape(-1,1)
type(val), val.shape

(numpy.ndarray, (4, 1))

In [6]:
y = onehot.fit_transform( val ).toarray()  
y

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [7]:
onehot_val = pd.DataFrame(y, dtype=int)
print(onehot_val)

df_new = pd.concat([df, onehot_val], axis=1)
df_new

   0  1  2  3
0  0  1  0  0
1  0  0  1  0
2  1  0  0  0
3  0  0  0  1


eng  라벨인코딩  0  1  2  3
0   b      1  0  1  0  0
1   c      2  0  0  1  0
2   a      0  1  0  0  0
3   d      3  0  0  0  1

# 레이블 인코딩, 원핫 인코딩 실습

In [8]:
data = { "회사명": ["MS","Apple", "Google", "Google"]}
df1 = pd.DataFrame(data)
df2 = df1.copy()
df2

회사명
0      MS
1   Apple
2  Google
3  Google

In [17]:
### LabelEncoder
encoder_x = LabelEncoder()
df1['lbl_en'] = encoder_x.fit_transform(df1['회사명'])  # 
df1

회사명  lbl_en
0      MS       2
1   Apple       0
2  Google       1
3  Google       1

In [20]:
#Onehot Encoder
onehot = OneHotEncoder()
y = onehot.fit_transform(df1['lbl_en'].values.reshape(-1,1) ).toarray()
print(y)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [21]:
# 변경된 값을 DataFrame형태로 변경
dx = pd.DataFrame(y, dtype=int)
df1_new = pd.concat([df1, dx], axis=1)
df1_new

회사명  lbl_en  0  1  2
0      MS       2  0  0  1
1   Apple       0  1  0  0
2  Google       1  0  1  0
3  Google       1  0  1  0

### 실습

In [22]:
### 01. 데이터 준비
import pandas as pd
data = { "feature1":[2,3,8,4],
         "feature2":[22,32,82,42],
         "target": ["b","c", "a", "d"]
       }
df = pd.DataFrame(data)
df

feature1  feature2 target
0         2        22      b
1         3        32      c
2         8        82      a
3         4        42      d

In [23]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
df['lbl_en'] = label_encoder.fit_transform(df['target'])
df

feature1  feature2 target  lbl_en
0         2        22      b       1
1         3        32      c       2
2         8        82      a       0
3         4        42      d       3

In [24]:
train_y = df['lbl_en'].values.reshape(len(df), 1)

onehot_encoder = preprocessing.OneHotEncoder(sparse=False)
train_y_onehot = onehot_encoder.fit_transform(train_y)
print(train_y_onehot)
print(train_y_onehot.shape)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [25]:
import pandas as pd
import os

In [26]:
demo_df = pd.DataFrame({"범주형_feature":['양말', '여우', '양말', '상자']})
display(demo_df)

범주형_feature
0          양말
1          여우
2          양말
3          상자

pandas의 get_dummies를 사용하면 간단히 사용 가능

In [27]:
onehot = pd.get_dummies(demo_df)
onehot

범주형_feature_상자  범주형_feature_양말  범주형_feature_여우
0               0               1               0
1               0               0               1
2               0               1               0
3               1               0               0

In [28]:
df = pd.concat([demo_df, onehot], axis=1)
df

범주형_feature  범주형_feature_상자  범주형_feature_양말  범주형_feature_여우
0          양말               0               1               0
1          여우               0               0               1
2          양말               0               1               0
3          상자               1               0               0